language: android
branches:
  only:
    - master
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-25
  - extra
  - addon

jobs:
  include:
    - stage: build
      jdk: oraclejdk8
      before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
      script: ./gradlew assembleDebug
    - stage: check
      jdk: oraclejdk8
      script: ./gradlew check